### PR TITLE
Build docker image with dind and ship with routes.

### LINKED ISSUE #8: Build docker image with DinD
To be able to use images in task directly without publishing on docker hub

### PR DESCRIPTION
**Pull request by La0**
Fixes #8

### CODE REVIEW

**Comment by jschwartzentruber** [comment]
Why have `decision_build_dind` separate? Isn't the artifact the same as `decision_build`?

**Comment by La0** [comment]
Yes, those would be the same docker images.
When the PR fully works, i'll remove the previous docker deployment to only rely on indexed images

It's still blocked by https://github.com/mozilla/community-tc-config/pull/198 though

**Comment by La0** [comment]
The scopes are now setup, the docker image is buitl through DinD and indexed : https://community-tc.services.mozilla.com/tasks/index/project.fuzzing.config.pull_request/fix-8

**Comment by La0** [comment]
fuzzing-tc-config is able [to use that image now](https://community-tc.services.mozilla.com/tasks/F6S0raZWQVeaNCszGE2uCA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FF6S0raZWQVeaNCszGE2uCA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log).

**Pull request merged**
